name: Deploy to Firebase Staging Hosting on Development PR
'on':
  pull_request:
    branches:
      - Development

env:
  ENVIRONMENT: staging

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create env file
        run: |
          touch .env
          echo "GA_env=STAGING" >> .env
      - run: npm ci && npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_REVIEWSAPP_94B53 }}'
          channelId: preview-channel
          projectId: smash2-d42c5
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
